// Fill out your copyright notice in the Description page of Project Settings.


#include "Placeables/GItemChest.h"

#include "Net/UnrealNetwork.h"


// Sets default values
AGItemChest::AGItemChest()
{
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

	BaseMesh = CreateDefaultSubobject<UStaticMeshComponent>("BaseMesh");
	RootComponent = BaseMesh;

	LidMesh = CreateDefaultSubobject<UStaticMeshComponent>("LidMesh");
	LidMesh->SetupAttachment(BaseMesh);

	TargetRoll = -110.0f;

	SetReplicates(true);
}

// Called when the game starts or when spawned
void AGItemChest::BeginPlay()
{
	Super::BeginPlay();
}

void AGItemChest::OnRep_LidOpened()
{
	float CurrPitch = bLidOpened ? TargetRoll : 0.0f;
	LidMesh->SetRelativeRotation(FRotator(0,0,CurrPitch));
}

// Called every frame
void AGItemChest::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

void AGItemChest::Interact_Implementation(APawn* InstigatorPawn)
{
	bLidOpened = !bLidOpened;
	OnRep_LidOpened();
}

// key function generated by UHT for replication rules
void AGItemChest::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);
	// 所有客户端同步bLidOpened变量
	DOREPLIFETIME(AGItemChest,bLidOpened);
}